
services:


  vacations-database-service:

    image: vacations-database-image

    build: ./Database

    container_name: vacations-database-container

    ports:
      - 3306:3306

    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: vacations
      MYSQL_USER: baruch
      MYSQL_PASSWORD: b1234
      MYSQL_RANDOM_ROOT_PASSWORD : 1

    
    restart: unless-stopped

    volumes:
      - vacations-volume:/var/lib/mysql



  vacations-backend-service:

    image: vacations-backend-image

    build: ./Backend

    container_name: vacations-backend-container

    ports:
      - 5000:3001

    environment:
      PORT: 3001
      MYSQL_HOST: vacations-database-service 
      MYSQL_DATABASE: vacations
      MYSQL_USER: baruch
      MYSQL_PASSWORD: b1234

    restart: unless-stopped

    volumes:
     
      - ./Backend:/app

    depends_on:
      - vacations-database-service



  vacations-frontend-service:

    image: vacations-frontend-image

    build: ./Frontend

    container_name: vacations-frontend-container

    ports:
      - 3000:3000

    environment:
      - WATCHPACK_POLLING=true 

    restart: unless-stopped

    volumes:
      - ./Frontend:/app

    depends_on:
      - vacations-database-service
      - vacations-backend-service

# ----------------phpmyadmin------------------------

  #  Name of the service:
  vacations-pma-service:

    image: phpmyadmin/phpmyadmin
    
    # Set name of the contianer:
    container_name: vacations-pma-container

    ports:
      - 8081:80

    environment:
      PMA_HOST: vacations-database-service

    links:
      - vacations-database-service

    restart: unless-stopped

    depends_on:
      - vacations-database-service



volumes:
  vacations-volume:

# docker-compose up -d --build
# docker-compose up -d --build


# docker-compose up
# docker-compose up -d

# 



